### ISSUE TITLE
掲載情報の追加

### ISSUE THREAD

**Issue by Kadoshita** [inct-densan-org/official-web#8]
* [ ] 活動実績
* [x] 問い合わせフォーム追加

**Comment by mak0tia** [comment]
- [ ] 問い合わせフォーム追加

**Comment by mak0tia** [comment]
#4 のIssueもまとめられるのでまとめました

**Comment by makotia** [comment]
問い合わせフォームを追加
https://github.com/inct-densan-org/official-web/commit/af1849a0f8e1bf0d8d32f8b13c817f898c57950f

**Comment by makotia** [comment]
コミットメッセージに書き忘れたけど活動実績
https://github.com/inct-densan-org/official-web/commit/0b02082a28e8542a18b51d79a409c6e8454d2660
